from rqalpha.const import SIDE, ORDER_TYPE, POSITION_EFFECT

from .vnpy import DIRECTION_LONG, DIRECTION_SHORT
from .vnpy import PRICETYPE_LIMITPRICE, PRICETYPE_MARKETPRICE
from .vnpy import OFFSET_CLOSE, OFFSET_OPEN

SIDE_MAPPING = {
    SIDE.BUY: DIRECTION_LONG,
    SIDE.SELL: DIRECTION_SHORT
}

ORDER_TYPE_MAPPING = {
    ORDER_TYPE.MARKET: PRICETYPE_MARKETPRICE,
    ORDER_TYPE.LIMIT: PRICETYPE_LIMITPRICE
}

POSITION_EFFECT_MAPPING = {
    POSITION_EFFECT.OPEN: OFFSET_OPEN,
    POSITION_EFFECT.CLOSE: OFFSET_CLOSE,
}

